- name: Cron
  hosts: all
  gather_facts: false

  tasks:
  # sudo crontab -l
  - name: Crontab configuration
    tags: docker
    block:

    - name: Daily backup job
      ansible.builtin.cron:
        name: "Backup databases and files (every day before 1AM): Vaultwarden, Mathesar PKMS"
        minute: 30
        hour: 0
        job: "{{ item }}"
        state: present
      loop:
        - "source ${SERVER_HOME}/env/services.env; source ${SERVER_HOME}/env/cron.env; mysqldump -h ${VAULTWARDEN_DB_IP} -u ${VAULTWARDEN_DB_USERNAME} -p${VAULTWARDEN_DB_PASSWORD} vaultwarden_db > /opt/backup/databases/vaultwarden.sql"
        - "source ${SERVER_HOME}/env/services.env; source ${SERVER_HOME}/env/cron.env; export PGPASSWORD=${MATHESAR_PKMS_DB_PASSWORD}; pg_dumpall -c -h ${MATHESAR_PKMS_DB_IP} -U ${MATHESAR_PKMS_DB_USERNAME} -l pkms_tables_db > /opt/backup/databases/mathesar-pkms.sql"

    - name: Weekly backup job
      ansible.builtin.cron:
        name: "Backup databases and files (every week before 2AM): Immich, Yamtrack"
        minute: 30
        hour: 1
        weekday: 1
        job: "{{ item }}"
        state: present
      loop:
        - "source ${SERVER_HOME}/env/services.env; source ${SERVER_HOME}/env/cron.env; export PGPASSWORD=${IMMICH_DB_PASSWORD}; pg_dumpall -c -h ${IMMICH_DB_IP} -U ${IMMICH_DB_USERNAME} -l immich_db > /opt/backup/databases/immich.sql"
        - "source ${SERVER_HOME}/env/services.env; source ${SERVER_HOME}/env/cron.env; export PGPASSWORD=${YAMTRACK_DB_PASSWORD}; pg_dumpall -c -h ${YAMTRACK_DB_IP} -U ${YAMTRACK_DB_USERNAME} -l yamtrack_db > /opt/backup/databases/yamtrack.sql"

    - name: Monthly backup job
      ansible.builtin.cron:
        name: "Backup databases and files (every month before 3AM): AdventureLog, FreshRSS, Guacamole, Change Detection, Pihole"
        minute: 30
        hour: 2
        day: 1
        job: "{{ item }}"
        state: present
      loop:
        - "source ${SERVER_HOME}/env/services.env; source ${SERVER_HOME}/env/cron.env; export PGPASSWORD=${ADVENTURELOG_DB_PASSWORD}; pg_dumpall -c -h ${ADVENTURELOG_DB_IP} -U ${ADVENTURELOG_DB_USERNAME} -l adventurelog > /opt/backup/databases/adventurelog.sql"
        - zip -r /opt/backup/files/adventurelog.zip /opt/persistence/adventurelog
        - "source ${SERVER_HOME}/env/services.env; source ${SERVER_HOME}/env/cron.env; export PGPASSWORD=${FRESHRSS_DB_PASSWORD}; pg_dumpall -c -h ${FRESHRSS_DB_IP} -U ${FRESHRSS_DB_USERNAME} -l postgres > /opt/backup/databases/freshrss.sql"
        - "source ${SERVER_HOME}/env/services.env; source ${SERVER_HOME}/env/cron.env; mysqldump -h ${GUACAMOLE_DB_IP} -u ${GUACAMOLE_DB_USERNAME} -p${GUACAMOLE_DB_PASSWORD} guacamole_db > /opt/backup/databases/guacamole.sql"
        - cp /opt/persistence/change-detection/changedetection-backup-* /opt/backup/files/changedetection.zip
        - "source ${SERVER_HOME}/env/.env; docker exec -w /etc/pihole pihole /bin/bash pihole -a -t; cp ${SERVER_HOME}/services/dns/pihole/etc-pihole/pi-hole-pihole-teleporter_* /opt/backup/files/pihole.tar.gz; docker exec pihole /bin/bash -c 'rm -f /etc/pihole/pi-hole-*'"

    - name: Minecraft backup job
      ansible.builtin.cron:
        name: "Backup Minecraft server (every month before 4AM)"
        minute: 30
        hour: 3
        day: 1
        job: "${SERVER_HOME}/scripts/backup/minecraft.sh"
        state: present
