- name: Cron
  hosts: all
  gather_facts: false

  tasks:
  # sudo crontab -l
  - name: Crontab configuration
    tags: docker
    block:

    - name: Daily backup job
      ansible.builtin.cron:
        name: "Backup databases (every day before 1AM): Immich, Vaultwarden"
        minute: 30
        hour: 0
        job: "{{ item }}"
        state: present
      loop:
        - "source ${SERVER_HOME}/env/services.env; source ${SERVER_HOME}/env/cron.env; mysqldump -h ${VAULTWARDEN_DB_IP} -u ${VAULTWARDEN_DB_USER} -p${VAULTWARDEN_DB_PASSWORD} vaultwarden_db > ${SERVER_HOME}/services/kopia/persistence/databases/vaultwarden.sql"

    - name: Weekly backup job
      ansible.builtin.cron:
        name: "Backup databases and files (every week before 2AM): Immich, Gitlab"
        minute: 30
        hour: 1
        weekday: 1
        job: "{{ item }}"
        state: present
      loop:
        - "source ${SERVER_HOME}/env/services.env; source ${SERVER_HOME}/env/cron.env; export PGPASSWORD=${IMMICH_POSTGRES_PASSWORD}; pg_dumpall -c -h ${IMMICH_DB_IP} -U ${IMMICH_POSTGRES_USER} -l immich_db > ${SERVER_HOME}/services/kopia/persistence/databases/immich.sql"
        - GITLAB_BACKUP_DIR=${SERVER_HOME}/services/kopia/persistence/files/gitlab; mkdir -p ${GITLAB_BACKUP_DIR}; docker exec -t gitlab gitlab-backup create BACKUP=dump; docker cp gitlab:/var/opt/gitlab/backups/dump_gitlab_backup.tar ${GITLAB_BACKUP_DIR}; docker cp gitlab:/etc/gitlab/gitlab.rb ${GITLAB_BACKUP_DIR}; docker cp gitlab:/etc/gitlab/gitlab-secrets.json ${GITLAB_BACKUP_DIR}

    - name: Files monthly backup job
      ansible.builtin.cron:
        name: "Backup files (every month before 3AM): Change Detection, Pihole"
        minute: 30
        hour: 2
        day: 1
        job: "{{ item }}"
        state: present
      loop:
        - source ${SERVER_HOME}/env/.env; cp ${SERVER_HOME}/services/monitoring/detection/persistence/changedetection-backup-* ${SERVER_HOME}/services/kopia/persistence/files/changedetection.zip
        - "source ${SERVER_HOME}/env/.env; docker exec -w /etc/pihole pihole /bin/bash pihole -a -t; cp ${SERVER_HOME}/services/dns/pihole/etc-pihole/pi-hole-pihole-teleporter_* ${SERVER_HOME}/services/kopia/persistence/files/pihole.tar.gz; docker exec pihole /bin/bash -c 'rm -f /etc/pihole/pi-hole-*'"

    - name: Minecraft backup job
      ansible.builtin.cron:
        name: "Backup Minecraft server (every month before 4AM)"
        minute: 30
        hour: 3
        day: 1
        job: "${SERVER_HOME}/scripts/backup/minecraft.sh"
        state: present
