services:
  unbound:
    container_name: unbound
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.11", "cloudflare.com"]
      interval: 60s
      timeout: 10s
    image: ${UNBOUND_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      dns-net:
        ipv4_address: ${UNBOUND_DNS_IP}
    ports:
      - 5335/tcp
      - 5335/udp
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /opt/persistence/unbound:/opt/unbound/etc/unbound
      # - /opt/persistence/unbound/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf:ro
      # - /opt/persistence/unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro

networks:
  dns-net:
    external: true
    name: dns-net
