- name: Doppler CLI
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
  # Dependencies
  - name: Dependencies
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ doppler_dependencies }}"
      package_type: dependencies

  # Repository
  # curl -fsSL --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo gpg --dearmor --output /usr/share/keyrings/doppler-archive-keyring.gpg
  # echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list > /dev/null
  - name: Repository
    tags: init
    ansible.builtin.include_tasks:
      file: ../tasks/repository.yml
    vars:
      key_url: https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key
      key_output: /etc/apt/keyrings/doppler-archive-keyring.gpg
      repository: "deb [signed-by=/etc/apt/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main"

  # Packages
  - name: Packages
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ doppler_packages }}"

  - name: Version
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/version.yml
    vars:
      cmd: doppler --version
