# https://github.com/pbogre/jetlog
services:
  jetlog:
    container_name: jetlog
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    hostname: jetlog
    image: ${JETLOG_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.jetlog.entrypoints=web,websecure"
      - "traefik.http.routers.jetlog.rule=Host(`${JETLOG_HOST}`)"
      - "traefik.http.routers.jetlog.tls=true"
      # - "traefik.http.routers.jetlog.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.jetlog.tls.domains[0].main=${JETLOG_HOST}"
      - "traefik.http.routers.jetlog.service=jetlog"
      # Services
      - "traefik.http.services.jetlog.loadbalancer.server.port=3000"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      proxy-net:
        ipv4_address: ${JETLOG_IP}
    ports:
      - 3000
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /opt/persistence/jetlog:/data

networks:
  proxy-net:
    external: true
    name: traefik-net
