# https://github.com/jordan-dalby/ByteStash
services:
  bytestash:
    cap_drop:
      - ALL
    container_name: bytestash
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --timeout=10 http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: bytestash
    image: ${BYTESTASH_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.bytestash.entrypoints=web-external,websecure-external"
      - "traefik.http.routers.bytestash.rule=Host(`snippets.${DOMAIN}`)"
      - "traefik.http.routers.bytestash.tls=true"
      # - "traefik.http.routers.bytestash.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.bytestash.tls.domains[0].main=snippets.${DOMAIN}"
      - "traefik.http.routers.bytestash.service=bytestash"
      # Services
      - "traefik.http.services.bytestash.loadbalancer.server.port=5000"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      proxy-net:
        ipv4_address: ${BYTESTASH_IP}
    ports:
      - 5000
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 30s
    user: ${USER_UID}:${USER_GID}
    volumes:
      - ./persistence:/data/snippets:rw

networks:
  proxy-net:
    external: true
    name: traefik-net
