# https://codeberg.org/forgejo/forgejo
services:
  cache:
    container_name: forgejo-valkey
    environment:
      - VALKEY_EXTRA_FLAGS=--requirepass ${FORGEJO_CACHE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli --raw INCR PING"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: forgejo-valkey
    image: ${DEFAULT_CACHE_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 2m
    networks:
      internal-net:
        ipv4_address: ${FORGEJO_CACHE_IP}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /mnt/ssd/cache/forgejo:/data
      - ./cache-persistence:/etc/valkey

  db:
    container_name: forgejo-postgres
    env_file: config/.env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${FORGEJO_DB_USERNAME}"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: forgejo-postgres
    image: ${DEFAULT_POSTGRES_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 5m
    networks:
      internal-net:
        ipv4_address: ${FORGEJO_DB_IP}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /mnt/ssd/databases/forgejo:/var/lib/postgresql/data

  forgejo:
    container_name: forgejo
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    hostname: forgejo
    image: ${FORGEJO_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      #- HTTP
      - "traefik.http.routers.forgejo.entrypoints=web,websecure"
      - "traefik.http.routers.forgejo.rule=Host(`${FORGEJO_HOST}`)"
      - "traefik.http.routers.forgejo.tls=true"
      # - "traefik.http.routers.forgejo.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.forgejo.tls.domains[0].main=${FORGEJO_HOST}"
      - "traefik.http.routers.forgejo.service=forgejo"
      #- TCP
      - "traefik.tcp.routers.forgejo-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.forgejo-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.forgejo-ssh.service=forgejo-ssh"
      # Services
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000"
      - "traefik.tcp.services.forgejo-ssh.loadbalancer.server.port=22"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      internal-net:
        ipv4_address: ${FORGEJO_INTERNAL_IP}
      proxy-net:
        ipv4_address: ${FORGEJO_IP}
    ports:
      - 22
      - 3000
    restart: unless-stopped
    stop_grace_period: 30s
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
      - ./persistence/data:/var/lib/gitea
      - ./persistence/conf:/etc/gitea
      - ./persistence/lfs:/data/lfs
      - ./persistence/log:/var/log/forgejo
      - /etc/localtime:/etc/localtime:ro

networks:
  internal-net:
    name: internal-forgejo
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${FORGEJO_NET}
          gateway: ${FORGEJO_GATEWAY}
  proxy-net:
    external: true
    name: traefik-net
