- name: Service Logs
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  - name: Initialize log directories
    tags: docker
    block:

    #--- Log directory
    - name: Create log root directory
      ansible.builtin.file:
        path: /mnt/hdd/log
        state: directory
        owner: docker
        group: docker
        mode: 0744

    #--- Services subdirectories
    - name: Create log subdirectories for all services
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: docker
        group: docker
        mode: 0744
      loop:
        - /mnt/hdd/log/ai/hermes
        - /mnt/hdd/log/ai/honcho
        - /mnt/hdd/log/ai/langfuse
        - /mnt/hdd/log/ai/litellm
        - /mnt/hdd/log/ai/ollama
        - /mnt/hdd/log/ai/openconcho
        - /mnt/hdd/log/ai/open-webui
        - /mnt/hdd/log/automation/n8n
        - /mnt/hdd/log/backup/kopia
        - /mnt/hdd/log/dashboard/homarr
        - /mnt/hdd/log/dashboard/homer
        - /mnt/hdd/log/development/directus
        - /mnt/hdd/log/dns/pihole
        - /mnt/hdd/log/dns/unbound
        - /mnt/hdd/log/finances/actual
        - /mnt/hdd/log/finances/wallos
        - /mnt/hdd/log/games/minecraft
        - /mnt/hdd/log/games/romm
        - /mnt/hdd/log/home/home-assistant
        - /mnt/hdd/log/home/upsnap
        - /mnt/hdd/log/inventory/grocy
        - /mnt/hdd/log/inventory/homebox
        - /mnt/hdd/log/inventory/hortusfox
        - /mnt/hdd/log/inventory/mealie
        - /mnt/hdd/log/inventory/wishlist
        - /mnt/hdd/log/management/cache/redis-insight
        - /mnt/hdd/log/management/code/bytestash
        - /mnt/hdd/log/management/code/forgejo
        - /mnt/hdd/log/management/code/gitea-mirror
        - /mnt/hdd/log/management/code/gitlab
        - /mnt/hdd/log/management/code/it-tools
        - /mnt/hdd/log/management/code/wakapi
        - /mnt/hdd/log/management/databases/dbgate
        - /mnt/hdd/log/management/passwords/vaultwarden
        - /mnt/hdd/log/media/sharing/gokapi
        - /mnt/hdd/log/media/storage/bookmarks/karakeep
        - /mnt/hdd/log/media/storage/books/kavita
        - /mnt/hdd/log/media/storage/books/librum
        - /mnt/hdd/log/media/storage/documents/nextcloud
        - /mnt/hdd/log/media/storage/documents/paperless
        - /mnt/hdd/log/media/storage/files/sftpgo
        - /mnt/hdd/log/media/storage/music/navidrome
        - /mnt/hdd/log/media/storage/news/freshrss
        - /mnt/hdd/log/media/storage/pictures/immich
        - /mnt/hdd/log/media/storage/pictures/meme-search
        - /mnt/hdd/log/media/storage/pictures/photoprism
        - /mnt/hdd/log/media/storage/pictures/pinry
        - /mnt/hdd/log/media/storage/videos/jellyfin
        - /mnt/hdd/log/media/tools/bento-pdf
        - /mnt/hdd/log/media/tools/convertx
        - /mnt/hdd/log/media/tools/docuseal
        - /mnt/hdd/log/media/tools/qbittorrent
        - /mnt/hdd/log/media/tools/stirling-pdf
        - /mnt/hdd/log/monitoring/change-detection
        - /mnt/hdd/log/monitoring/diun
        - /mnt/hdd/log/monitoring/dozzle
        - /mnt/hdd/log/monitoring/grafana
        - /mnt/hdd/log/monitoring/ntfy
        - /mnt/hdd/log/monitoring/prometheus
        - /mnt/hdd/log/monitoring/scrutiny
        - /mnt/hdd/log/other/limesurvey
        - /mnt/hdd/log/pkms/affine
        - /mnt/hdd/log/pkms/mathesar
        - /mnt/hdd/log/pkms/memos
        - /mnt/hdd/log/pkms/obsidian
        - /mnt/hdd/log/proxy/traefik
        - /mnt/hdd/log/remote/guacamole
        - /mnt/hdd/log/remote/rustdesk
        - /mnt/hdd/log/remote/wg-easy
        - /mnt/hdd/log/remote/wireguard
        - /mnt/hdd/log/search/camofox
        - /mnt/hdd/log/search/searxng
        - /mnt/hdd/log/security/authentik
        - /mnt/hdd/log/security/crowdsec
        - /mnt/hdd/log/security/enclosed
        - /mnt/hdd/log/security/gluetun
        - /mnt/hdd/log/security/wazuh
        - /mnt/hdd/log/travel/adventurelog
        - /mnt/hdd/log/travel/dawarich
        - /mnt/hdd/log/travel/jetlog
