# https://github.com/browserless/browserless
services:
  browserless:
    container_name: browserless-multi
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/pressure"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: browserless-multi
    image: ${BROWSERLESS_MULTI_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      proxy-net:
        ipv4_address: ${BROWSERLESS_MULTI_IP}
    ports:
      - 3000
    restart: unless-stopped
    stop_grace_period: 30s

networks:
  proxy-net:
    external: true
    name: traefik-net
