# https://github.com/paperless-ngx/paperless-ngx
services:
  cache:
    container_name: paperless-valkey
    environment:
      - VALKEY_EXTRA_FLAGS=--maxmemory-policy noeviction --requirepass ${PAPERLESS_CACHE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli --raw INCR PING"]
      interval: 20s
      retries: 3
      start_interval: 5s
      start_period: 60s
      timeout: 15s
    hostname: paperless-valkey
    image: ${DEFAULT_CACHE_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 2m
    networks:
      internal-net:
        ipv4_address: ${PAPERLESS_CACHE_IP}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /mnt/ssd/cache/paperless:/data

  db:
    container_name: paperless-postgres
    env_file: config/.env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PAPERLESS_DB_USER}"]
      interval: 20s
      retries: 3
      start_interval: 5s
      start_period: 60s
      timeout: 15s
    hostname: paperless-postgres
    image: ${DEFAULT_POSTGRES_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 5m
    networks:
      internal-net:
        ipv4_address: ${PAPERLESS_DB_IP}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /mnt/ssd/databases/paperless:/var/lib/postgresql/data

  gotenberg:
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command: gotenberg --chromium-disable-javascript=true --chromium-allow-list=file:///tmp/.*
    container_name: paperless-gotenberg
    hostname: paperless-gotenberg
    image: ${GOTENBERG_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 2m
    networks:
      internal-net:
        ipv4_address: ${PAPERLESS_GOTENBERG_IP}
    restart: unless-stopped
    stop_grace_period: 30s

  tika:
    container_name: paperless-tika
    hostname: paperless-tika
    image: ${TIKA_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 2m
    networks:
      internal-net:
        ipv4_address: ${PAPERLESS_TIKA_IP}
    restart: unless-stopped
    stop_grace_period: 30s

  paperless:
    container_name: paperless
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
      gotenberg:
        condition: service_started
      tika:
        condition: service_started
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: paperless
    image: ${PAPERLESS_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.paperless.entrypoints=web,websecure"
      - "traefik.http.routers.paperless.rule=Host(`${PAPERLESS_HOST}`)"
      - "traefik.http.routers.paperless.tls=true"
      # - "traefik.http.routers.paperless.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.paperless.tls.domains[0].main=${PAPERLESS_HOST}"
      - "traefik.http.routers.paperless.service=paperless"
      # Services
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      internal-net:
        ipv4_address: ${PAPERLESS_INTERNAL_IP}
      proxy-net:
        ipv4_address: ${PAPERLESS_IP}
    ports:
      - 8000
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /opt/persistence/paperless/consume:/usr/src/paperless/consume
      - /opt/persistence/paperless/data:/usr/src/paperless/data
      - /opt/persistence/paperless/export:/usr/src/paperless/export
      - opt/persistence/paperless/media:/usr/src/paperless/media

networks:
  internal-net:
    name: internal-paperless
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PAPERLESS_NET}
          gateway: ${PAPERLESS_GATEWAY}
  proxy-net:
    external: true
    name: traefik-net
