# - Instead of SQLite (default), MariaDB is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
# https://github.com/paperless-ngx/paperless-ngx
services:
  cache:
    container_name: paperless-valkey
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli --raw INCR PING"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: paperless-valkey
    image: ${DEFAULT_CACHE_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 2m
    networks:
      internal-net:
        ipv4_address: ${PAPERLESS_CACHE_IP}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /mnt/ssd/cache/paperless:/data

  db:
    container_name: paperless-mariadb
    env_file: config/.env.db
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${PAPERLESS_DB_ROOT_PASSWORD}"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: paperless-mariadb
    image: ${DEFAULT_DB_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 5m
    networks:
      internal-net:
        ipv4_address: ${PAPERLESS_DB_IP}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /mnt/ssd/databases/paperless:/var/lib/mysql

  gotenberg:
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command: gotenberg --chromium-disable-javascript=true --chromium-allow-list=file:///tmp/.*
    container_name: paperless-gotenberg
    hostname: paperless-gotenberg
    image: ${GOTENBERG_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 2m
    networks:
      internal-net:
        ipv4_address: ${PAPERLESS_GOTENBERG_IP}
    restart: unless-stopped
    stop_grace_period: 30s

  tika:
    container_name: paperless-tika
    hostname: paperless-tika
    image: ${TIKA_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 2m
    networks:
      internal-net:
        ipv4_address: ${PAPERLESS_TIKA_IP}
    restart: unless-stopped
    stop_grace_period: 30s

  paperless:
    # createsuperuser --noinput --username "${PAPERLESS_ADMIN_USER}" --email "${USER_EMAIL}"
    container_name: paperless
    depends_on:
      cache:
        condition: service_started
      db:
        condition: service_healthy
      gotenberg:
        condition: service_started
      tika:
        condition: service_started
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: paperless
    image: ${PAPERLESS_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.paperless.entrypoints=web,websecure"
      - "traefik.http.routers.paperless.rule=Host(`${PAPERLESS_HOST}`)"
      - "traefik.http.routers.paperless.tls=true"
      # - "traefik.http.routers.paperless.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.paperless.tls.domains[0].main=${PAPERLESS_HOST}"
      - "traefik.http.routers.paperless.service=paperless"
      # Services
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      internal-net:
        ipv4_address: ${PAPERLESS_INTERNAL_IP}
      proxy-net:
        ipv4_address: ${PAPERLESS_IP}
    ports:
      - 8000
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./persistence/consume:/usr/src/paperless/consume
      - ./persistence/data:/usr/src/paperless/data
      - ./persistence/export:/usr/src/paperless/export
      - ./persistence/media:/usr/src/paperless/media

networks:
  internal-net:
    name: internal-paperless
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PAPERLESS_NET}
          gateway: ${PAPERLESS_GATEWAY}
  proxy-net:
    external: true
    name: traefik-net
