- name: XRDP
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # Packages
  - name: Packages
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ xrdp_packages }}"

  # Service
  - name: Service
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/service.yml
    vars:
      service: xrdp

  # User
  - name: User
    tags: init
    block:

    # sudo groupadd -g 1002 rdp
    - name: Create group
      ansible.builtin.group:
        name: rdp
        gid: "{{ rdp_gid }}"
        state: present

    # sudo useradd -c "RDP" -g rdp -m -d /home/rdp -s /bin/bash -u 1002 rdp
    - name: Create user
      ansible.builtin.user:
        name: rdp
        uid: "{{ rdp_uid }}"
        group: rdp
        home: /home/rdp
        shell: /bin/bash
        comment: RDP
        state: present

    # sudo usermod -a -G ssl-cert rdp
    - name: Add RDP user to ssl-cert group
      ansible.builtin.user:
        name: rdp
        groups: ssl-cert
        append: true
