services:
  gitlab:
    container_name: gitlab
    dns:
      - 127.0.0.1
      - 45.90.28.96
      - 45.90.30.96
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url "https://gitlab.${DOMAIN}"
        registry_external_url "https://registry.gitlab.${DOMAIN}"
        pages_external_url "https://pages.gitlab.${DOMAIN}"
        # Container Registry
        registry['enable'] = true
        gitlab_rails['registry_enabled'] = true
        # LFS
        gitlab_rails['lfs_enabled'] = true
        # Pages
        gitlab_pages['inplace_chroot'] = true
        gitlab_pages['external_http'] = ['gitlab:5201']
        # Reverse proxy
        #- General
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['http2_enabled'] = false
        nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        nginx['redirect_http_to_https'] = false
        nginx['hsts_max_age'] = 0
        nginx['hsts_include_subdomains'] = true
        #- Registry
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 5000
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        #- Pages
        pages_nginx['enable'] = true
        pages_nginx['listen_port'] = 5200
        pages_nginx['listen_https'] = false
        pages_nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        # SMTP
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_HOST}"
        gitlab_rails['smtp_domain'] = "${SMTP_HOST}"
        gitlab_rails['smtp_port'] = "${SMTP_PORT}"
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        #gitlab_rails['smtp_tls'] = false
        gitlab_rails['gitlab_email_from'] = "noreply-gitlab@${DOMAIN}"
        #gitlab_rails['gitlab_email_reply_to'] = "gitlab@${DOMAIN}"
        # SSH
        gitlab_rails['gitlab_ssh_host'] = "gitlab.${DOMAIN}"
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    image: ${GITLAB_IMAGE}
    hostname: gitlab
    labels:
      - "traefik.enable=true"
      # Routers
      #- HTTP
      #-- Instance
      - "traefik.http.routers.gitlab.entrypoints=web,websecure"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.${DOMAIN}`)"
      - "traefik.http.routers.gitlab.tls=true"
      # - "traefik.http.routers.gitlab.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.gitlab.tls.domains[0].main=gitlab.${DOMAIN}"
      - "traefik.http.routers.gitlab.service=gitlab"
      #-- Registry
      - "traefik.http.routers.gitlab-registry.entrypoints=web,websecure"
      - "traefik.http.routers.gitlab-registry.rule=Host(`registry.gitlab.${DOMAIN}`)"
      - "traefik.http.routers.gitlab-registry.tls=true"
      # - "traefik.http.routers.gitlab-registry.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.gitlab-registry.tls.domains[0].main=gitlab.${DOMAIN}"
      - "traefik.http.routers.gitlab-registry.service=gitlab-registry"
      #-- Pages
      - "traefik.http.routers.gitlab-pages.entrypoints=web,websecure"
      - "traefik.http.routers.gitlab-pages.rule=Host(`pages.gitlab.${DOMAIN}`)"
      - "traefik.http.routers.gitlab-pages.tls=true"
      # - "traefik.http.routers.gitlab-pages.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.gitlab-pages.tls.domains[0].main=gitlab.${DOMAIN}"
      - "traefik.http.routers.gitlab-pages.service=gitlab-pages"
      #- TCP
      - "traefik.tcp.routers.gitlab-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh"
      # Services
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      - "traefik.http.services.gitlab-registry.loadbalancer.server.port=5000"
      - "traefik.http.services.gitlab-pages.loadbalancer.server.port=5201"
      - "traefik.tcp.services.gitlab-ssh.loadbalancer.server.port=22"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      traefik-net:
        ipv4_address: ${GITLAB_IP}
    ports:
      - 22
      - 80
      - 5000
      - 5201
    restart: always
    shm_size: 256m
    stop_grace_period: 30s
    volumes:
      - ./persistence/config:/etc/gitlab
      - ./persistence/logs:/var/log/gitlab
      - ./persistence/data:/var/opt/gitlab

networks:
  traefik-net:
    external: true
    name: traefik-net
