services:
  gitlab:
    container_name: gitlab
    dns:
      - 127.0.0.1
      - 45.90.28.96
      - 45.90.30.96
    env_file: config/.env
    image: ${GITLAB_IMAGE}
    hostname: gitlab
    labels:
      - "traefik.enable=true"
      # Routers
      # - HTTP
      #   - Instance
      - "traefik.http.routers.gitlab.entrypoints=web,websecure"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.${DOMAIN}`)"
      - "traefik.http.routers.gitlab.tls=true"
      # - "traefik.http.routers.gitlab.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.gitlab.tls.domains[0].main=gitlab.${DOMAIN}"
      - "traefik.http.routers.gitlab.service=gitlab"
      #   - Registry
      - "traefik.http.routers.gitlab-registry.entrypoints=web,websecure"
      - "traefik.http.routers.gitlab-registry.rule=Host(`registry.gitlab.${DOMAIN}`)"
      - "traefik.http.routers.gitlab-registry.tls=true"
      # - "traefik.http.routers.gitlab-registry.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.gitlab-registry.tls.domains[0].main=gitlab.${DOMAIN}"
      - "traefik.http.routers.gitlab-registry.service=gitlab-registry"
      # - TCP
      #- "traefik.tcp.routers.gitlab-ssh.entrypoints=ssh"
      #- "traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`gitlab.${DOMAIN}`)"
      #- "traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh"
      # Services
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      - "traefik.http.services.gitlab-registry.loadbalancer.server.port=5000"
      #- "traefik.tcp.services.gitlab-ssh.loadbalancer.server.port=22"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      traefik-net:
        ipv4_address: ${GITLAB_IP}
    ports:
      - ${GITLAB_SSH_PORT}:22
      - 80
      - 5000
    restart: always
    shm_size: 256m
    stop_grace_period: 30s
    volumes:
      - ./persistence/config:/etc/gitlab
      - ./persistence/logs:/var/log/gitlab
      - ./persistence/data:/var/opt/gitlab

networks:
  traefik-net:
    external: true
    name: traefik-net
