services:
  kavita:
    container_name: kavita
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    hostname: kavita
    image: ${KAVITA_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.kavita.entrypoints=web,websecure"
      - "traefik.http.routers.kavita.rule=Host(`${KAVITA_HOST}`)"
      - "traefik.http.routers.kavita.tls=true"
      # - "traefik.http.routers.kavita.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.kavita.tls.domains[0].main=${KAVITA_HOST}"
      - "traefik.http.routers.kavita.service=kavita"
      # Services
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      traefik-net:
        ipv4_address: ${KAVITA_IP}
    ports:
      - 5000
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /opt/persistence/kavita/books:/books
      - /opt/persistence/kavita/comics:/comics
      - /opt/persistence/kavita/config:/kavita/config
      - /opt/persistence/kavita/manga:/manga

networks:
  traefik-net:
    external: true
    name: traefik-net
