services:
  pihole:
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    container_name: pihole
    #domainname: ${PIHOLE_HOST}
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    hostname: pihole
    image: ${PIHOLE_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.pihole.entrypoints=web,websecure"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_HOST}`)"
      - "traefik.http.routers.pihole.tls=true"
      # - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.pihole.tls.domains[0].main=${PIHOLE_HOST}"
      - "traefik.http.routers.pihole.middlewares=pihole-cors"
      - "traefik.http.routers.pihole.service=pihole"
      # Middlewares
      - "traefik.http.middlewares.pihole-cors.headers.accesscontrolallowmethods=GET,POST"
      - "traefik.http.middlewares.pihole-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.pihole-cors.headers.accesscontrolalloworiginlist=https://${HOMER_HOST}"
      - "traefik.http.middlewares.pihole-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.pihole-cors.headers.addvaryheader=true"
      # Services
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      proxy-net:
        ipv4_address: ${PIHOLE_IP}
      dns-net:
        ipv4_address: ${PIHOLE_DNS_IP}
      monitoring-net:
        ipv4_address: ${PIHOLE_MONITORING_IP}
    ports:
      # DNS Ports
      - ${PIHOLE_DNS_PORT}:53/tcp
      - ${PIHOLE_DNS_PORT}:53/udp
      #- 67:67/udp # Only required if you are using Pi-hole as your DHCP server
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      # run `touch ./pihole.log` first unless you like errors
      - /opt/persistence/pihole/pihole.log:/var/log/pihole.log
      - /opt/persistence/pihole/etc-pihole:/etc/pihole
      - /opt/persistence/pihole/etc-dnsmasqd:/etc/dnsmasq.d

networks:
  proxy-net:
    external: true
    name: traefik-net
  dns-net:
    external: true
    name: dns-net
  monitoring-net:
    external: true
    name: monitoring-net
