# https://github.com/directus/directus
services:
  cache:
    command: redis-server --requirepass ${DIRECTUS_CACHE_PASSWORD}
    container_name: directus-redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --raw INCR PING"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: directus-redis
    image: ${DEFAULT_REDIS_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 2m
    networks:
      internal-net:
        ipv4_address: ${DIRECTUS_CACHE_IP}
    restart: unless-stopped
    stop_grace_period: 30s

  db:
    container_name: directus-postgres
    env_file: config/.env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DIRECTUS_DB_USER}"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: directus-postgres
    image: ${DEFAULT_POSTGRES_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 5m
    networks:
      internal-net:
        ipv4_address: ${DIRECTUS_DB_IP}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /mnt/ssd/databases/directus:/var/lib/postgresql/data

  directus:
    container_name: directus
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    env_file: config/.env
    hostname: directus
    image: ${DIRECTUS_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.directus.entrypoints=web,websecure"
      - "traefik.http.routers.directus.rule=Host(`${DIRECTUS_HOST}`)"
      - "traefik.http.routers.directus.tls=true"
      # - "traefik.http.routers.directus.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.directus.tls.domains[0].main=${DIRECTUS_HOST}"
      - "traefik.http.routers.directus.service=directus"
      # Services
      - "traefik.http.services.directus.loadbalancer.server.port=8055"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      internal-net:
        ipv4_address: ${DIRECTUS_INTERNAL_IP}
      proxy-net:
        ipv4_address: ${DIRECTUS_IP}
    ports:
      - 8055
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./persistence/uploads:/directus/uploads
      - ./persistence/extensions:/directus/extensions

networks:
  internal-net:
    name: internal-directus
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DIRECTUS_NET}
          gateway: ${DIRECTUS_GATEWAY}
  proxy-net:
    external: true
    name: traefik-net
