services:
  scrutiny:
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    container_name: scrutiny
    devices:
      - /dev/nvme0
      - /dev/sda
    dns:
      - 127.0.0.1
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    hostname: scrutiny
    image: ${SCRUTINY_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      ## Default
      - "traefik.http.routers.scrutiny.entrypoints=web,websecure"
      - "traefik.http.routers.scrutiny.rule=Host(`${SCRUTINY_HOST}`) && !ClientIP(`${PUBLIC_IP}`)"
      - "traefik.http.routers.scrutiny.tls=true"
      # - "traefik.http.routers.scrutiny.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.scrutiny.tls.domains[0].main=${SCRUTINY_HOST}"
      # - "traefik.http.routers.scrutiny.middlewares=scrutiny"
      - "traefik.http.routers.scrutiny.service=scrutiny"
      ## API access router without authentication
      - "traefik.http.routers.scrutiny-homer.entrypoints=web,websecure"
      - "traefik.http.routers.scrutiny-homer.rule=Host(`${SCRUTINY_HOST}`) && ClientIP(`${PUBLIC_IP}`) && PathPrefix(`/api/summary`)"
      - "traefik.http.routers.scrutiny-homer.tls=true"
      # - "traefik.http.routers.scrutiny-homer.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.scrutiny-homer.tls.domains[0].main=${SCRUTINY_HOST}"
      - "traefik.http.routers.scrutiny-homer.middlewares=scrutiny-cors"
      - "traefik.http.routers.scrutiny-homer.service=scrutiny"
      # Middlewares
      ## Auth
      # - "traefik.http.middlewares.scrutiny.basicauth.users=${SCRUTINY_USER}:${SCRUTINY_PASSWORD}"
      ## CORS
      - "traefik.http.middlewares.scrutiny-cors.headers.accessControlAllowOriginList=https://${HOMER_HOST}"
      - "traefik.http.middlewares.scrutiny-cors.headers.accessControlAllowMethods=GET,OPTIONS"
      - "traefik.http.middlewares.scrutiny-cors.headers.accessControlAllowHeaders=Content-Type,Authorization"
      - "traefik.http.middlewares.scrutiny-cors.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.scrutiny-cors.headers.addVaryHeader=true"
      # Services
      - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      proxy-net:
        ipv4_address: ${SCRUTINY_IP}
    ports:
      - 8080
      - 8086
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /opt/persistence/scrutiny/config:/opt/scrutiny/config
      - /opt/persistence/scrutiny/influxdb:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro

networks:
  proxy-net:
    external: true
    name: traefik-net
